plugins:
    jekyll-relative-links
relative_links:
    enabled: true
    collections: true
include:
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    - helpful.js
    - helpful.min.js
    - helpful.min.js.map